### ISSUE TITLE
Mixin conflict with Lenient Stack Size.

### ISSUE THREAD

**Issue by bomkz** [vlad2305m/AkashicTomeOfToolsFabric#1]
Hi there, it seems there's a mixin conflict between both of these mods, concerning akashictomeoftools.mixins.json:AnvilScreenHandler_2ndSlotDecrementMixin and lenientstacksize.mixins.json:AnvilScreenHandlerMixin
[latest.log](https://github.com/vlad2305m/AkashicTomeOfToolsFabric/files/7776135/latest.log)

**Comment by vlad2305m** [comment]
Just open this mod's jar in an archive manager, open akashictomeoftools.mixins.json with a text editor and delete anythig you want except ItemStack_SubstitutionMixin, MinecraftClient_HandleInput_AttackMixin and PacketByteBuf_ItemNetworkingMixin. (Everything else may conflict, so if you want to stack unstackables, their implementation is probably better and may be compatible with this mod)
There is no core mod to fix the issues once and for all, so I have no idea how to get around random people doing the same thing in different mods (and someone actually doing an incopmatible different thing).

**Comment by bomkz** [comment]
> Just open this mod's jar in an archive manager, open akashictomeoftools.mixins.json with a text editor and delete anythig 

Understandable, thank you!
