### ISSUE TITLE
Book says "Bricked" When crafted

### ISSUE THREAD

**Issue by 3th3** [vlad2305m/AkashicTomeOfToolsFabric#10]
The askashic tome says "bricked" when crafted and when you switch to a book you can't switch back. I don't know if it saying bricked means anything but I know that it not switching back is not intended. The only thing I can think of that might mess it up is a mod called [Better combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus) but I am unsure on the nature of what bricked means

**Comment by 3th3** [comment]
Just realised I wasn't doing it right, sorry haha

**Comment by vlad2305m** [comment]
Bricked when crafting is a limitation of vanilla minecraft I can't find a nice workaround to. It isn't an issue until the book is bricked in any other way than crafting.
Same for better combat: the user input system is very  complex, so I just went for a solution that works. You can change the "look up" list in the settings or config file. 
Have fun `^ω^`!
