### ISSUE TITLE
tomes randomly breaking?

### ISSUE THREAD

**Issue by nillawafers4u** [vlad2305m/AkashicTomeOfToolsFabric#4]
hey, for about 3 days your mod was working perfectly. but now for some reason I'm unable to change the book into anything else besides what it already was. after throwing the book down all items have disappeared from the tome.

getting on my server today after restarting clients + server tomes seem to no longer function and all of them have lost their inventories

I'm on minecraft version 1.18.1

fabric 0.12.12

**Comment by vlad2305m** [comment]
@rsjonah please provide startup log of your server. 

Furthermore, if you can, send me nbt data of tomes at different stages in the processes of losing the items (eg. hold it, run `/data get entity @s SelectedItem`, throw it, run `/data get entity [UID of the dropped stack]`, pick it up, run 1st command again). (`/data get ...` is probably logged as well as the rest of the chat, so if you comment on what you are doing in chat, a log file will suffice.)
