### ISSUE TITLE
Crash on 1.18.1 Another Quality modpack 2

### ISSUE THREAD

**Issue by itsdinkd** [vlad2305m/AkashicTomeOfToolsFabric#5]
Minecraft Version
1.18.1

Akashic Tome v1.2

**Describe the crash or bug**
I Tried to use the akashic tomb after adding some books to it then when I tried to change it back to the akashic tomb it went to the server menu and said I couldn't connect, after that when I rejoined my world and tried it again my game crashed and crashes whenever I open it there were 4 books in it
Modern industrialization, croparia, end for dummies, and I don't remember that last one

**Steps to reproduce the behavior:**
I also made a copy of the world after the update and instead of automatically crashing it went to the server screen and said I had disconnected from the server even though I'm on single player beyond this i do not know

**Expected behavior**
for it to change back to akashic tome

Crash log or latest.log.log
https://paste-bin.xyz/42670

**Comment by vlad2305m** [comment]
It looks like NbtCrafting's old issue https://github.com/Siphalor/nbt-crafting/issues/64
⇒ Incompatible with NbtCrafting (for now)

**Comment by Siphalor** [comment]
@itsdinkd
I don't know how you're launching the mod pack, but it'd be extremely helpful if you could follow these steps to get some more insights:
- Add `-Dmixin.debug=true` to the launch arguments
- Look for the file `.mixin.out/class/net/minecraft/class_1799` in the `.minecraft` folder and upload it

This file contains valuable information in what's actually happening, as I assume to be a mod compatibility issue or at least want to rule that out.

Alternatively if you're using any published mod pack, you can post the link to that, and I can do some experimenting on my own.

**Comment by itsdinkd** [comment]
The modpack is Another Quality modpack 2. Thanks

**Comment by itsdinkd** [comment]
Version 2.1 (not 2.1.1) has akashic tome in it
