### ISSUE TITLE
Crash when added to All of Fabric 5 Modpack

### ISSUE THREAD

**Issue by bigtruckin78** [vlad2305m/AkashicTomeOfToolsFabric#6]
Can't get the modpack to load when I add this mod. Getting an invalid mixin. 
[latest.log](https://github.com/vlad2305m/AkashicTomeOfToolsFabric/files/8969612/latest.log)
.

**Comment by vlad2305m** [comment]
Does it not crash without this mod?

**Comment by vlad2305m** [comment]
Did you set `-Dmixin.debug`? If yes, change to `-Dmixin.debug.export -Dmixin.debug.verbose`

**Comment by bigtruckin78** [comment]
Tried without -Dmixin.debug and still would not load. Pack will load without this mod. FWIW Removed Charm mod and the pack loaded up with Akashic just fine.

**Comment by vlad2305m** [comment]
> Tried without -Dmixin.debug

log ?
> Removed Charm mod and the pack loaded up with Akashic just fine.

That's the charm of debugging large modpacks...

**Comment by bigtruckin78** [comment]
I changed to -Dmixin.debug.export -Dmixin.debug.verbose and here is the log with charm added back in.
[latest.log](https://github.com/vlad2305m/AkashicTomeOfToolsFabric/files/8970487/latest.log)

**Comment by vlad2305m** [comment]
[akashictomeoftools-1.2.1_charmfix-1.zip](https://github.com/vlad2305m/AkashicTomeOfToolsFabric/files/8970734/akashictomeoftools-1.2.1_charmfix-1.zip)
Here, try this one instead (it seems to be in a little debate over how to not lose your books in the anvil)

**Comment by bigtruckin78** [comment]
Seems to be working like a charm... Thanks for your time.

**Comment by vlad2305m** [comment]
It was a pleasure. 
(Updating to 1.19 atm)

**Comment by cyleaf** [comment]
having the same problem with the charm interaction on the current 1.19 version of akashictomeoftoolsfabric
