### ISSUE TITLE
Akashic tome of records and Charm mod crash

### ISSUE THREAD

**Issue by DanMeadWasTaken** [vlad2305m/AkashicTomeOfToolsFabric#9]
https://paste.ee/p/YnbVM

**Comment by DanMeadWasTaken** [comment]
As a side note, I updated to 1.3.7 of akashic tome of tools mod, and It still spits out the same exact error

**Comment by vlad2305m** [comment]
Caused by incompatibility with charm. I will have to look at that in the
next weekend.

**Comment by DanMeadWasTaken** [comment]
Alright, take your time, I have almost 600 hundred mods in this pack(s) so it'll take me awhile to do all the testing I need to do anyway- Not to mention, I'm waiting on some other mods to update as well.

**Comment by AndreAugustoDev** [comment]
I also confirm that it causes crashes
Even with the large amount of mods, Charm + Akashic Tome is the cause of this specific crash

https://mclo.gs/qigtWDs

**Comment by vlad2305m** [comment]
Fixed. You will have to delete "stackable_enchanted_books.FixAnvilBookStackMixin" from charm manually until the charm dev fixes it as well
